#task-queue-broker
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: vv8-crawler-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        volumeMounts:
        - name: redis-storage
          mountPath: /data
          subPath: redis
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        ports:
          - containerPort: 5432
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: vv8-crawler-data-pvc
---
# Redis Servce
apiVersion: v1
kind: Service
metadata:
  name: task-queue-broker  # TODO: THIS SHOULDN'T BE HARDCODED BASED ON DOCKERFILE
  namespace: vv8-crawler-general
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
---
# Really Hacky way og getting the mongo-initdb script to run
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
  namespace: vv8-crawler-general
data: # See cat mongo-init.js | base64
  mongo-init.js: |
    ZGIuY3JlYXRlVXNlcigKICAgIHsKICAgICAgICB1c2VyOiAndnY4JywKICAgICAgICBwd2Q6ICd2djgnLAogICAgICAgIHJvbGVzOiBbCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgIHJvbGU6ICJyb290IiwKICAgICAgICAgICAgICAgIGRiOiAndnY4JwogICAgICAgICAgICB9CiAgICAgICAgXQogICAgfQopOw==
---
# mongodb-deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: vv8-crawler-general
spec:
  replicas: 1
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        command: ["docker-entrypoint.sh"]
        args: ["mongod", "--wiredTigerCacheSizeGB", "2.0"]
        env:
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: vv8
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: vv8
        volumeMounts:
        - name: "init-database"
          mountPath: "/docker-entrypoint-initdb.d/"
        - name: mongodb-storage
          mountPath: /data/db
          subPath: mongodb
        resources:
          limits:
            cpu: "8"
            memory: "8Gi"
        ports:
          - containerPort: 27017
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: vv8-crawler-data-pvc
      - name: "init-database"
        configMap:
          name: mongo-init
---
# MongoDB service
apiVersion: v1
kind: Service
metadata:
  name: mongodb  # TODO: THIS SHOULDN'T BE HARDCODED BASED ON DOCKERFILE
  namespace: vv8-crawler-general
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb
---
# flower-deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flower-deployment
  namespace: vv8-crawler-general
spec:
  replicas: 1
  serviceName: flower
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      initContainers:
      - name: init-task-queue-broker
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup task-queue-broker.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for Task Queue Broker; sleep 2; done"]
      containers:
      - name: flower
        image: registry.k3s.kapravelos.com/insecure_flower:latest
        env:
          - name: CELERY_BROKER
            value: task-queue-broker
        volumeMounts:
        - name: flower-storage
          mountPath: /data
          subPath: flower
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: flower-storage
        persistentVolumeClaim:
          claimName: vv8-crawler-data-pvc
---
# log_parser_worker
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: log-parser-worker
  namespace: vv8-crawler-general
spec:
  replicas: 1
  serviceName: log-parser-worker
  selector:
    matchLabels:
      app: log-parser-worker
  template:
    metadata:
      labels:
        app: log-parser-worker
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
      - name: init-task-queue-broker
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup task-queue-broker.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for Task Queue Broker; sleep 2; done"]
      - name: init-postgresql-container
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup postgresql-container.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgresql-container; sleep 2; done"]
      containers:
      - name: lpw-container
        image: registry.k3s.kapravelos.com/log-parser-worker:latest
        env:
          - name: ADBLOCK_BINARY
            value: /app/post-processors/adblock
          - name: CELERY_CONCURRENCY
            value: "4" # TODO: Change this or have an automatic way to provide this!
          - name: EASYLIST_FILE
            value: /app/post-processors/easylist.txt
          - name: EASYPRIVACY_FILE
            value: /app/post-processors/easyprivacy.txt
          - name: EMAP_FILE
            value: /app/post-processors/entities.json
          - name: IDLDATA_FILE
            value: /artifacts/idldata.json
          - name: MONGODB_AUTHDB
            value: admin
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_PWD
            value: vv8
          - name: MONGODB_USER
            value: vv8
          - name: PGDATABASE
            value: vv8_backend
          - name: PGHOST
            value: postgresql-container
          - name: PGPASSWORD
            value: vv8
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            value: vv8
          - name: VV8_CELERY_BROKER
            value: task-queue-broker
          - name: VV8_CELERY_BROKER_PORT
            value: "6379"
          - name: VV8_CELERY_ID
            value: vv8_log_parser
        volumeMounts:
          - mountPath: /app/raw_logs
            name: vv8-log-parser-vol
            subPath: vv8-crawler-raw-logs
          - mountPath: /app/parsed_logs
            name: vv8-log-parser-vol
            subPath: vv8-crawler-parsed-logs
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
      volumes:
        - name: vv8-log-parser-vol
          persistentVolumeClaim:
            claimName: vv8-crawler-data-pvc
---
# postgresql-pod
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-pod
  namespace: vv8-crawler-general
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-container
  template:
    metadata:
      labels:
        app: postgresql-container
    spec:
      containers:
      - name: postgresql-container
        image: registry.k3s.kapravelos.com/vv8_database:latest
        env:
          - name: POSTGRES_USER
            value: vv8
          - name: POSTGRES_PASSWORD
            value: vv8
          - name: POSTGRES_DB
            value: vv8_backend
        ports:
          - containerPort: 5432
        resources:
          limits:
            cpu: "8"
            memory: "8Gi"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-data
            subPath: postgresql
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
              claimName: vv8-crawler-data-pvc
---
# postgresql-container service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-container  # TODO: THIS SHOULDN'T BE HARDCODED BASED ON DOCKERFILE
  namespace: vv8-crawler-general
spec:
  selector:
    app: postgresql-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgresql-container
---
# VV8 Crawler worker
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vv8-crawler-worker
  namespace: vv8-crawler-general
spec:
  serviceName: vv8-crawler-worker
  replicas: 1
  selector:
    matchLabels:
      app: vv8-crawler-worker
  template:
    metadata:
      labels:
        app: vv8-crawler-worker
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
      - name: init-task-queue-broker
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup task-queue-broker.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for Task Queue Broker; sleep 2; done"]
      - name: init-postgresql-container
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup postgresql-container.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgresql-container; sleep 2; done"]
      containers:
      - name: vv8-worker
        image: registry.k3s.kapravelos.com/vv8_crawler_worker:latest
        env:
            - name: CELERY_CONCURRENCY
              value: "4"
            - name: EXTRA_CELERY_ARGS
              value: "--prefetch-multiplier=1"
            - name: MONGO_DATABASE
              value: admin
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PASSWORD
              value: vv8
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: vv8
            - name: VV8_CELERY_BROKER
              value: task-queue-broker
            - name: VV8_CELERY_BROKER_PORT
              value: "6379"
            - name: VV8_CELERY_ID
              value: vv8_worker
        terminationGracePeriodSeconds: 600 # The pods can take their time and finish any crawls they gotta do! 
        ports:
          - containerPort: 5901
          - containerPort: 6901
        resources:
          limits:
            cpu: "8"
            memory: "4Gi"
        volumeMounts:
          - mountPath: /app/screenshots
            name: vv8-worker-vol
            subPath: vv8-worker-screenshots
          - mountPath: /app/har
            name: vv8-worker-vol
            subPath: vv8-worker-har
          - mountPath: /app/vv8_worker/raw_logs
            name: vv8-worker-vol
            subPath: vv8-crawler-raw-logs
      volumes:
        - name: vv8-worker-vol
          persistentVolumeClaim:
            claimName: vv8-crawler-data-pvc 
---
# Backend API
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vv8-backend
  namespace: vv8-crawler-general
spec:
  serviceName: vv8-backend
  selector:
    matchLabels:
      app: vv8-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: vv8-backend
    spec:
      initContainers:
      - name: init-task-queue-broker
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup task-queue-broker.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for Task Queue Broker; sleep 2; done"]
      - name: init-postgresql-container
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup postgresql-container.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgresql-container; sleep 2; done"]
      containers:
      - name: vv8-backend
        image: registry.k3s.kapravelos.com/vv8_backend:latest
        env:
          - name: VV8_CELERY_BROKER
            value: task-queue-broker
          - name: VV8_CELERY_BROKER_PORT
            value: "6379"
          - name: VV8_CELERY_ID
            value: vv8_web_server
          - name: SQL_USERNAME
            value: vv8
          - name: SQL_PASSWORD
            value: vv8
          - name: SQL_HOST
            value: postgresql-container
          - name: SQL_PORT
            value: "5432"
          - name: SQL_DATABASE
            value: vv8_backend
          - name: MONGO_HOST
            value: mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_USER
            value: vv8
          - name: MONGO_PASSWORD
            value: vv8
          - name: MONGO_DATABASE
            value: admin
        ports:
          - containerPort: 4000
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
---
# Backend API Service
apiVersion: v1
kind: Service
metadata:
  name: vv8-backend
  namespace: vv8-crawler-general
spec:
  selector:
    app: vv8-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: vv8-backend
---
# Jypter Notebook
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter-notebook
  namespace: vv8-crawler-general
spec:
  replicas: 1
  serviceName: jupyter-notebook
  selector:
    matchLabels:
      name: jupyterlab
  template:
    metadata:
      labels:
        name: jupyterlab
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: jupyterlab
          image: jupyter/datascience-notebook:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888
          command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --LabApp.token='SomethingComplexAndCompleXAndBuffer' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
          volumeMounts:
            - name: jupyterlab-data
              mountPath: /home/jovyan
              subPath: jupyterlab
            - name: jupyterlab-data
              mountPath: /data
          resources:
            requests:
              memory: "3Gi"
              cpu: "4"
      restartPolicy: Always
      volumes:
      - name: jupyterlab-data
        persistentVolumeClaim:
          claimName: vv8-crawler-data-pvc
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject # Please check https://keda.sh/docs/2.12/concepts/scaling-deployments/
metadata:
  name: vv8-crawler-worker-scaler
  namespace: vv8-crawler-general
spec:
  scaleTargetRef:
    name: vv8-crawler-worker
    kind: StatefulSet
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
  - type: redis
    metadata:
      listName: crawler
      address: task-queue-broker.vv8-crawler-general:6379
      listLength: "124"
